the commit where i make some relics
Cartopol/STS_Community_Warlord_Mod pull request #19
Opened 2020-05-07 03:35 UTC by squeeny

adds the relics:
medic pouch, pocketknife, fencing gloves, feather boots, samurai sword

2020-05-07 20:04 UTC, Cartopol requested changes
Looks really good, Squeeny! There's an improvement that can be made to use the OnParrySubscriber interface for relics, if you're up for it. Other than that, looks really good!

2020-05-07 20:04 UTC, Cartopol commented on src/main/java/the_warlord/powers/ParryPower.java
>              //this calls onParry for all powers that implement onParrySubsciber
For these types of things I created the onParrySubscriber interface. Every time you parry, I call onParry() on all powers and all cards that have implemented this interface. So instead of adding these functions to the ParryPower, it is done in an onParry method of the power or card itself. 
I haven't implemented this system yet for relics, and I don't mind doing that part. But if you want to learn how this works, check out a power like QuickDrawPower. To do the same for relics, you would have to add the following stuff in the ParryPower:
`for (AbstractRelic relic : p.relics) {
if (relic instanceof OnParrySubscriber) {
relic.onParry(isFullParrying) }
}`
In other words, for each relic, check if it implements the OnParrySubscriber interface. If it does, call the relic's onParry method. 

This kind of subscriber model makes it much easier to implement functionality in the class that should have it, instead of implementing it in methods of other classes.

2020-05-08 10:40 UTC, squeeny commented
pushed a commit with the relevant changes

2020-05-08 16:23 UTC, Cartopol approved these changes

2020-05-08 16:23 UTC, merged